@startuml
title Analysis Class Diagram - UC018 UpdateOrRemoveItem

class "UpdateItemUI" as UI <<boundary>> {
  + selectItemAction() : void
  + displayUpdate() : void
}
class "ShoppingItemController" as Controller <<control>> {
  + updateOrRemoveItem(action: String, itemId: String, data: Data) : void
}
class "ShoppingDB" as Entity <<entity>> {
  + executeItemDbAction(action: String, itemId: String, data: Data) : Boolean
}

Controller -- UI
Controller -- Entity
@enduml
