@startuml
title Analysis Class Diagram - UC016 ManageShoppingList

class "ManageListUI" as UI <<boundary>> {
  + selectAction() : void
  + displayUpdate() : void
}
class "ManageListController" as Controller <<control>> {
  + handleListAction(action: String, listId: String, data: Data) : void
}
class "ShoppingDB" as Entity <<entity>> {
  + executeDbQuery(action: String, listId: String, data: Data) : Boolean
}

Controller -- UI
Controller -- Entity
@enduml
