@startuml
title Analysis Class Diagram - UC022 UpdateFoodInfo

class "UpdateFoodUI" as UI <<boundary>> {
  + selectFoodToUpdate() : void
  + displayUpdate() : void
}
class "FoodManagementController" as Controller <<control>> {
  + updateFood(foodId: String, updatedData: Data) : void
}
class "PantryDB" as Entity <<entity>> {
  + updateFoodData(foodId: String, updatedData: Data) : Boolean
}

Controller -- UI
Controller -- Entity
@enduml
