@startuml
title Combined Communication Diagram - Module_7_Statistics

' Cấu hình nét thẳng và tắt đổ bóng
skinparam linetype ortho
skinparam shadowing false

' Tăng khoảng cách mặc định lên cao để tạo không gian rộng rãi
skinparam nodesep 250
skinparam ranksep 200
skinparam defaultTextAlignment center

' Xóa bỏ vòng tròn phân loại (E) và làm sạch bên trong khối
hide circle
hide empty members

' Cấu hình đồng bộ màu vàng
skinparam {
    ActorBackgroundColor #FFFFCC
    BoundaryBackgroundColor #FFFFCC
    ControlBackgroundColor #FFFFCC
    EntityBackgroundColor #FFFFCC
    ClassBackgroundColor #FFFFCC
}

allow_mixing

actor "User" as User_Alias
boundary "StatisticsDashboardUI" as StatisticsDashboardUI_Alias
control "StatisticsController" as StatisticsController_Alias
entity "StatDB" as StatDB_Alias

User_Alias -right--- StatisticsDashboardUI_Alias  : " ▶ 1: Chọn khoảng thời gian "
StatisticsDashboardUI_Alias -right---- StatisticsController_Alias  : " ▶ 2: getStatistics() \n ◀ 4: trả dữ liệu "
StatisticsController_Alias -down- StatDB_Alias  : " ▼ 3: queryUsageAndWasteData() "

@enduml
