@startuml
title Analysis Class Diagram - UC034 ViewStatistics

class "StatisticsDashboardUI" as UI <<boundary>> {
  + selectDateRange() : void
  + renderChart() : void
}
class "StatisticsController" as Controller <<control>> {
  + getStatistics(dateRange: Data) : void
}
class "StatDB" as Entity <<entity>> {
  + queryUsageAndWasteData(dateRange: Data) : Data
}

Controller -- UI
Controller -- Entity
@enduml
