@startuml
title Communication Diagram - UC029 SuggestRecipes

' Cấu hình nét thẳng và tắt đổ bóng
skinparam linetype ortho
skinparam shadowing false

' Tăng khoảng cách mặc định lên cao để tạo không gian rộng rãi
skinparam nodesep 250
skinparam ranksep 200
skinparam defaultTextAlignment center

' Xóa bỏ vòng tròn phân loại (E) và làm sạch bên trong khối
hide circle
hide empty members

' Cấu hình đồng bộ màu vàng
skinparam {
    ActorBackgroundColor #FFFFCC
    BoundaryBackgroundColor #FFFFCC
    ControlBackgroundColor #FFFFCC
    EntityBackgroundColor #FFFFCC
    ClassBackgroundColor #FFFFCC
}

allow_mixing
actor "User" as Actor
boundary "SuggestRecipeUI" as UI
control "AISuggestionController" as Controller
entity "PantryDB" as PantryDB
control "AIService" as AIService

Actor -right--- UI : " ▶ 1: Gợi ý món ăn "
UI -right---- Controller : " ▶ 2: getSuggestions() \n ◀ 6: trả kết quả "
Controller -down- PantryDB : " ▼ 3: getAvailableIngredients() "
Controller -right- AIService : " ▶ 4: generateRecipes() "
@enduml
