@startuml
title Analysis Class Diagram - UC031 BookmarkRecipe

class "BookmarkRecipeUI" as UI <<boundary>> {
  + clickBookmark() : void
  + displayUpdate() : void
}
class "BookmarkController" as Controller <<control>> {
  + toggleBookmark(recipeId: String, userId: String) : void
}
class "RecipeDB" as Entity <<entity>> {
  + updateBookmarkStatus(recipeId: String, userId: String) : Boolean
}

Controller -- UI
Controller -- Entity
@enduml
