@startuml
title Communication Diagram - UC032 AddMissingIngredients

' Cấu hình nét thẳng và tắt đổ bóng
skinparam linetype ortho
skinparam shadowing false

' Tăng khoảng cách mặc định lên cao để tạo không gian rộng rãi
skinparam nodesep 250
skinparam ranksep 200
skinparam defaultTextAlignment center

' Xóa bỏ vòng tròn phân loại (E) và làm sạch bên trong khối
hide circle
hide empty members

' Cấu hình đồng bộ màu vàng
skinparam {
    ActorBackgroundColor #FFFFCC
    BoundaryBackgroundColor #FFFFCC
    ControlBackgroundColor #FFFFCC
    EntityBackgroundColor #FFFFCC
    ClassBackgroundColor #FFFFCC
}

allow_mixing
actor "User" as Actor
boundary "MissingIngredientUI" as UI
control "ShoppingIntegrationController" as Controller
entity "PantryDB" as PantryDB
control "ShoppingController" as ShoppingController
entity "ShoppingDB" as ShoppingDB

Actor -right--- UI : " ▶ 1: Thêm nguyên liệu thiếu "
UI -right---- Controller : " ▶ 2: findMissingIngredients() \n ◀ 7: trả kết quả "
Controller -down- PantryDB : " ▼ 3: checkAvailable() "
Controller -right- ShoppingController : " ▶ 4: addItemsToList() "
ShoppingController -down- ShoppingDB : " ▼ 5: saveItems() "
@enduml
