@startuml
title Communication Diagram - UC031 BookmarkRecipe

' Cấu hình nét thẳng và tắt đổ bóng
skinparam linetype ortho
skinparam shadowing false

' Tăng khoảng cách mặc định lên cao để tạo không gian rộng rãi
skinparam nodesep 250
skinparam ranksep 200
skinparam defaultTextAlignment center

' Xóa bỏ vòng tròn phân loại (E) và làm sạch bên trong khối
hide circle
hide empty members

' Cấu hình đồng bộ màu vàng
skinparam {
    ActorBackgroundColor #FFFFCC
    BoundaryBackgroundColor #FFFFCC
    ControlBackgroundColor #FFFFCC
    EntityBackgroundColor #FFFFCC
    ClassBackgroundColor #FFFFCC
}

allow_mixing
actor "User" as Actor
boundary "BookmarkRecipeUI" as UI
control "BookmarkController" as Controller
entity "RecipeDB" as Entity

Actor -right--- UI : " ▶ 1: Click lưu công thức "
UI -right---- Controller : " ▶ 2: toggleBookmark() \n ◀ 4: trả kết quả "
Controller -down- Entity : " ▼ 3: updateBookmarkStatus() "
@enduml
