@startuml
title Analysis Class Diagram - UC013 RemoveMember

class "RemoveMemberUI" as UI <<boundary>> {
  + selectMemberToRemove() : void
  + displayResult() : void
}
class "MemberController" as Controller <<control>> {
  + removeMember(groupId: String, memberId: String) : void
}
class "FamilyDB" as Entity <<entity>> {
  + deleteMember(groupId: String, memberId: String) : Boolean
}

Controller -- UI
Controller -- Entity
@enduml
