@startuml
title Analysis Class Diagram - UC037 ManageMasterData

class "MasterDataUI" as UI <<boundary>> {
  + manageData() : void
  + displayUpdate() : void
}
class "MasterDataController" as Controller <<control>> {
  + executeCRUD(action: String, data: Data) : void
}
class "MasterDataDB" as Entity <<entity>> {
  + updateDatabase(action: String, data: Data) : Boolean
}

Controller -- UI
Controller -- Entity
@enduml
