@startuml
title Analysis Class Diagram - UC035 AdminLoginAndViewUsers

class "UserManagementUI" as UI <<boundary>> {
  + login() : void
  + viewUsers() : void
}
class "UserManagementController" as Controller <<control>> {
  + loginAdmin(credentials: Data) : void
  + getUsersList(filters: Data) : void
}
class "UserDB" as Entity <<entity>> {
  + queryAllUsers(filters: Data) : List
}

Controller -- UI
Controller -- Entity
@enduml
