@startuml
title Combined Communication Diagram - Module_5_MealPlanner

' Cấu hình nét thẳng và tắt đổ bóng
skinparam linetype ortho
skinparam shadowing false

' Tăng khoảng cách mặc định lên cao để tạo không gian rộng rãi
skinparam nodesep 250
skinparam ranksep 200
skinparam defaultTextAlignment center

' Xóa bỏ vòng tròn phân loại (E) và làm sạch bên trong khối
hide circle
hide empty members

' Cấu hình đồng bộ màu vàng
skinparam {
    ActorBackgroundColor #FFFFCC
    BoundaryBackgroundColor #FFFFCC
    ControlBackgroundColor #FFFFCC
    EntityBackgroundColor #FFFFCC
    ClassBackgroundColor #FFFFCC
}

allow_mixing

actor "User" as User_Alias
boundary "ViewMealPlanUI" as ViewMealPlanUI_Alias
control "MealPlanController" as MealPlanController_Alias
entity "MealPlanDB" as MealPlanDB_Alias
boundary "ManageMealSessionUI" as ManageMealSessionUI_Alias
control "MealSessionController" as MealSessionController_Alias
boundary "RemoveMealUI" as RemoveMealUI_Alias

User_Alias -right--- ViewMealPlanUI_Alias  : " ▶ 1: Mở Lịch trình "
ViewMealPlanUI_Alias -right---- MealPlanController_Alias  : " ▶ 2: getMealPlan() \n ◀ 4: trả kết quả "
MealPlanController_Alias -down- MealPlanDB_Alias  : " ▼ 3: querySessions() "
User_Alias -right--- ManageMealSessionUI_Alias  : " ▶ 1: Chọn & gán món ăn "
ManageMealSessionUI_Alias -right---- MealSessionController_Alias  : " ▶ 2: addOrUpdateMeal() \n ◀ 4: trả kết quả "
MealSessionController_Alias -down- MealPlanDB_Alias  : " ▼ 3: saveMealToSession() "
User_Alias -right--- RemoveMealUI_Alias  : " ▶ 1: Chọn xóa món ăn "
RemoveMealUI_Alias -right---- MealSessionController_Alias  : " ▶ 2: removeMeal() \n ◀ 4: trả kết quả "
MealSessionController_Alias -down- MealPlanDB_Alias  : " ▼ 3: deleteMeal() "

@enduml
