@startuml
title Analysis Class Diagram - UC008 CreateFamilyGroup

class "CreateGroupUI" as UI <<boundary>> {
  + enterGroupName() : void
  + displayResult() : void
}
class "CreateGroupController" as Controller <<control>> {
  + createGroup(groupName: String) : void
}
class "FamilyDB" as Entity <<entity>> {
  + saveNewGroup(groupName: String, ownerId: String) : String
}

Controller -- UI
Controller -- Entity
@enduml
