@startuml
title Analysis Class Diagram - UC009 ViewFamilyMembers

class "ViewGroupUI" as UI <<boundary>> {
  + requestGroupDetails() : void
  + displayGroupData() : void
}
class "ViewGroupController" as Controller <<control>> {
  + getGroupDetails(groupId: String) : void
}
class "FamilyDB" as Entity <<entity>> {
  + queryGroupInfoAndMembers(groupId: String) : Data
}

Controller -- UI
Controller -- Entity
@enduml
