@startuml
title Communication Diagram - UC013 RemoveMember

' Cấu hình nét thẳng và tắt đổ bóng
skinparam linetype ortho
skinparam shadowing false

' Tăng khoảng cách mặc định lên cao để tạo không gian rộng rãi
skinparam nodesep 250
skinparam ranksep 200
skinparam defaultTextAlignment center

' Xóa bỏ vòng tròn phân loại (E) và làm sạch bên trong khối
hide circle
hide empty members

' Cấu hình đồng bộ màu vàng
skinparam {
    ActorBackgroundColor #FFFFCC
    BoundaryBackgroundColor #FFFFCC
    ControlBackgroundColor #FFFFCC
    EntityBackgroundColor #FFFFCC
    ClassBackgroundColor #FFFFCC
}

allow_mixing
actor "User (Admin)" as Actor
boundary "RemoveMemberUI" as UI
control "MemberController" as Controller
entity "FamilyDB" as Entity

Actor -right--- UI : " ▶ 1: Chọn xóa thành viên "
UI -right---- Controller : " ▶ 2: removeMember() \n ◀ 4: trả kết quả "
Controller -down- Entity : " ▼ 3: deleteMember() "
@enduml
