@startuml
title Analysis Class Diagram - UC012 UpdateMemberRole

class "ManageRoleUI" as UI <<boundary>> {
  + selectRole() : void
  + displayUpdate() : void
}
class "RoleController" as Controller <<control>> {
  + updateRole(groupId: String, memberId: String, newRole: String) : void
}
class "FamilyDB" as Entity <<entity>> {
  + updateMemberRole(groupId: String, memberId: String, newRole: String) : Boolean
}

Controller -- UI
Controller -- Entity
@enduml
