@startuml
title Communication Diagram - UC034 ViewStatistics

' Cấu hình nét thẳng và tắt đổ bóng
skinparam linetype ortho
skinparam shadowing false

' Tăng khoảng cách mặc định lên cao để tạo không gian rộng rãi
skinparam nodesep 250
skinparam ranksep 200
skinparam defaultTextAlignment center

' Xóa bỏ vòng tròn phân loại (E) và làm sạch bên trong khối
hide circle
hide empty members

' Cấu hình đồng bộ màu vàng
skinparam {
    ActorBackgroundColor #FFFFCC
    BoundaryBackgroundColor #FFFFCC
    ControlBackgroundColor #FFFFCC
    EntityBackgroundColor #FFFFCC
    ClassBackgroundColor #FFFFCC
}

allow_mixing
actor "User" as Actor
boundary "StatisticsDashboardUI" as UI
control "StatisticsController" as Controller
entity "StatDB" as Entity

Actor -right--- UI : " ▶ 1: Chọn khoảng thời gian "
UI -right---- Controller : " ▶ 2: getStatistics() \n ◀ 4: trả dữ liệu "
Controller -down- Entity : " ▼ 3: queryUsageAndWasteData() "
@enduml
