@startuml
title Analysis Class Diagram - UC039 ViewAdminDashboard

class "AdminDashboardUI" as UI <<boundary>> {
  + requestDashboardData() : void
  + displayDashboard() : void
}
class "AdminDashboardController" as Controller <<control>> {
  + getOverviewStats() : void
}
class "SystemDB" as Entity <<entity>> {
  + querySystemMetrics() : Data
}

Controller -- UI
Controller -- Entity
@enduml
