@startuml
title Communication Diagram - UC030 ViewRecipeDetail

' Cấu hình nét thẳng và tắt đổ bóng
skinparam linetype ortho
skinparam shadowing false

' Tăng khoảng cách mặc định lên cao để tạo không gian rộng rãi
skinparam nodesep 250
skinparam ranksep 200
skinparam defaultTextAlignment center

' Xóa bỏ vòng tròn phân loại (E) và làm sạch bên trong khối
hide circle
hide empty members

' Cấu hình đồng bộ màu vàng
skinparam {
    ActorBackgroundColor #FFFFCC
    BoundaryBackgroundColor #FFFFCC
    ControlBackgroundColor #FFFFCC
    EntityBackgroundColor #FFFFCC
    ClassBackgroundColor #FFFFCC
}

allow_mixing
actor "User" as Actor
boundary "SearchRecipeUI" as UI
control "RecipeSearchController" as Controller
entity "RecipeDB" as Entity

Actor -right--- UI : " ▶ 1: Tìm kiếm & Xem chi tiết "
UI -right---- Controller : " ▶ 2: searchRecipes() / getRecipeDetail() \n ◀ 4: trả kết quả "
Controller -down- Entity : " ▼ 3: queryRecipes() / queryRecipeById() "
@enduml
