@startuml
title Communication Diagram - UC033 ChatWithAIChef

' Cấu hình nét thẳng và tắt đổ bóng
skinparam linetype ortho
skinparam shadowing false

' Tăng khoảng cách mặc định lên cao để tạo không gian rộng rãi
skinparam nodesep 250
skinparam ranksep 200
skinparam defaultTextAlignment center

' Xóa bỏ vòng tròn phân loại (E) và làm sạch bên trong khối
hide circle
hide empty members

' Cấu hình đồng bộ màu vàng
skinparam {
    ActorBackgroundColor #FFFFCC
    BoundaryBackgroundColor #FFFFCC
    ControlBackgroundColor #FFFFCC
    EntityBackgroundColor #FFFFCC
    ClassBackgroundColor #FFFFCC
}

allow_mixing
actor "User" as Actor
boundary "AIChatUI" as UI
control "ChatController" as Controller
control "AIService" as AIService

Actor -right--- UI : " ▶ 1: Nhập câu hỏi "
UI -right---- Controller : " ▶ 2: sendMessage() \n ◀ 4: trả kết quả "
Controller -right- AIService : " ▶ 3: callAiAPI() "
@enduml
