@startuml
title Analysis Class Diagram - UC027 ManageMeal

class "ManageMealSessionUI" as UI <<boundary>> {
  + assignMealToSession() : void
  + displayResult() : void
}
class "MealSessionController" as Controller <<control>> {
  + addOrUpdateMeal(sessionId: String, recipeId: String) : void
}
class "MealPlanDB" as Entity <<entity>> {
  + saveMealToSession(sessionId: String, recipeId: String) : Boolean
}

Controller -- UI
Controller -- Entity
@enduml
