@startuml
title Analysis Class Diagram - UC026 ViewMealPlan

class "ViewMealPlanUI" as UI <<boundary>> {
  + selectDateRange() : void
  + displayMealPlan() : void
}
class "MealPlanController" as Controller <<control>> {
  + getMealPlan(dateRange: Data) : void
  + createSession(date: Date, type: String) : void
}
class "MealPlanDB" as Entity <<entity>> {
  + querySessions(dateRange: Data) : List
  + insertSession(date: Date, type: String) : String
}

Controller -- UI
Controller -- Entity
@enduml
