@startuml
title Sequence Diagram - UC015 CreateShoppingList

actor "User" as Actor
boundary "CreateShoppingListUI" as UI
control "CreateListController" as Controller
entity "ShoppingDB" as Entity

Actor -> UI : 1. Nhập tên danh sách & Nhấn "Tạo"
activate UI
UI -> Controller : 2. createList(listName, groupId)
activate Controller
Controller -> Entity : 3. saveNewList(listName, groupId)
activate Entity
Entity --> Controller : 4. return listId
deactivate Entity
Controller --> UI : 5. Thông báo tạo thành công
deactivate Controller
UI --> Actor : 6. Hiển thị danh sách mua sắm mới
deactivate UI
@enduml
