@startuml
title Analysis Class Diagram - UC015 CreateShoppingList

class "CreateShoppingListUI" as UI <<boundary>> {
  + inputListName() : void
  + displayResult() : void
}
class "CreateListController" as Controller <<control>> {
  + createList(listName: String, groupId: String) : void
}
class "ShoppingDB" as Entity <<entity>> {
  + saveNewList(listName: String, groupId: String) : String
}

Controller -- UI
Controller -- Entity
@enduml
