@startuml
title Communication Diagram - UC019 FinishShopping

' Cấu hình nét thẳng và tắt đổ bóng
skinparam linetype ortho
skinparam shadowing false

' Tăng khoảng cách mặc định lên cao để tạo không gian rộng rãi
skinparam nodesep 250
skinparam ranksep 200
skinparam defaultTextAlignment center

' Xóa bỏ vòng tròn phân loại (E) và làm sạch bên trong khối
hide circle
hide empty members

' Cấu hình đồng bộ màu vàng
skinparam {
    ActorBackgroundColor #FFFFCC
    BoundaryBackgroundColor #FFFFCC
    ControlBackgroundColor #FFFFCC
    EntityBackgroundColor #FFFFCC
    ClassBackgroundColor #FFFFCC
}

allow_mixing
actor "User" as Actor
boundary "MarkItemBoughtUI" as UI
control "ShoppingItemController" as Controller
entity "ShoppingDB" as ShoppingDB
control "PantryController" as PantryController
entity "PantryDB" as PantryDB

Actor -right--- UI : " ▶ 1: Đánh dấu đã mua "
UI -right---- Controller : " ▶ 2: markItemAsBought() \n ◀ 9: trả thông báo "
Controller -down- ShoppingDB : " ▼ 3: updateItemStatus() "
Controller -right- PantryController : " ▶ 5: transferItemToPantry() "
PantryController -down- PantryDB : " ▼ 6: addFood() "
@enduml
