@startuml
title Sequence Diagram - UC017 AddItemToList

actor "User" as Actor
boundary "AddShoppingItemUI" as UI
control "ShoppingItemController" as Controller
entity "ShoppingDB" as Entity

Actor -> UI : 1. Nhập tên mặt hàng, số lượng & Thêm
activate UI
UI -> Controller : 2. addItem(listId, itemName, quantity)
activate Controller
Controller -> Entity : 3. saveItem(listId, itemName, quantity)
activate Entity
Entity --> Controller : 4. return itemId
deactivate Entity
Controller --> UI : 5. Thông báo thêm thành công
deactivate Controller
UI --> Actor : 6. Cập nhật danh sách mặt hàng
deactivate UI
@enduml
