@startuml
title Communication Diagram - UC024 AutoDeductFood

' Cấu hình nét thẳng và tắt đổ bóng
skinparam linetype ortho
skinparam shadowing false

' Tăng khoảng cách mặc định lên cao để tạo không gian rộng rãi
skinparam nodesep 250
skinparam ranksep 200
skinparam defaultTextAlignment center

' Xóa bỏ vòng tròn phân loại (E) và làm sạch bên trong khối
hide circle
hide empty members

' Cấu hình đồng bộ màu vàng
skinparam {
    ActorBackgroundColor #FFFFCC
    BoundaryBackgroundColor #FFFFCC
    ControlBackgroundColor #FFFFCC
    EntityBackgroundColor #FFFFCC
    ClassBackgroundColor #FFFFCC
}

allow_mixing
actor "User" as Actor
boundary "MealPlanUI" as UI
control "MealController" as MealController
control "PantryController" as PantryController
entity "PantryDB" as PantryDB

Actor -right--- UI : " ▶ 1: Xác nhận nấu xong "
UI -right---- MealController : " ▶ 2: confirmMealCooked() \n ◀ 7: trả kết quả "
MealController -down- PantryController : " ▼ 3: deductIngredients() "
PantryController -down- PantryDB : " ▼ 4: decreaseFoodQuantity() "
@enduml
