@startuml
title Analysis Class Diagram - UC020 ViewPantry

class "ViewPantryUI" as UI <<boundary>> {
  + enterSearchKeyword() : void
  + displayFoodList() : void
}
class "PantrySearchController" as Controller <<control>> {
  + searchFood(keyword: String, filters: Data) : void
}
class "PantryDB" as Entity <<entity>> {
  + queryFoodList(keyword: String, filters: Data) : List
}

Controller -- UI
Controller -- Entity
@enduml
