@startuml
title Analysis Class Diagram - UC021 AddFoodManually

class "AddFoodUI" as UI <<boundary>> {
  + inputFoodDetails() : void
  + displaySuccess() : void
}
class "FoodManagementController" as Controller <<control>> {
  + addFood(foodDetails: Data) : void
}
class "PantryDB" as Entity <<entity>> {
  + saveFood(foodDetails: Data) : String
}

Controller -- UI
Controller -- Entity
@enduml
