@startuml
title Communication Diagram - UC025 ExpiryNotification

' Cấu hình nét thẳng và tắt đổ bóng
skinparam linetype ortho
skinparam shadowing false

' Tăng khoảng cách mặc định lên cao để tạo không gian rộng rãi
skinparam nodesep 250
skinparam ranksep 200
skinparam defaultTextAlignment center

' Xóa bỏ vòng tròn phân loại (E) và làm sạch bên trong khối
hide circle
hide empty members

' Cấu hình đồng bộ màu vàng
skinparam {
    ActorBackgroundColor #FFFFCC
    BoundaryBackgroundColor #FFFFCC
    ControlBackgroundColor #FFFFCC
    EntityBackgroundColor #FFFFCC
    ClassBackgroundColor #FFFFCC
}

allow_mixing
actor "System (CronJob)" as Cron
control "NotificationController" as Controller
entity "PantryDB" as DB
control "NotificationService" as NotifService
actor "User" as Actor

Cron -right--- Controller : " ▶ 1: triggerCheckExpiryDaily() "
Controller -right---- DB : " ▶ 2: queryExpiringFoods() \n ◀ 3: trả list "
Controller -down- NotifService : " ▼ 4: sendExpiryWarning() "
NotifService -down- Actor : " ▼ 5: gửi thông báo "
@enduml
