@startuml
title Sequence Diagram - UC021 AddFoodManually

actor "User" as Actor
boundary "AddFoodUI" as UI
control "FoodManagementController" as Controller
entity "PantryDB" as Entity

Actor -> UI : 1. Nhập thông tin thực phẩm (Tên, SL, HSD, Thể loại) & Thêm
activate UI
UI -> Controller : 2. addFood(foodDetails)
activate Controller
Controller -> Entity : 3. saveFood(foodDetails)
activate Entity
Entity --> Controller : 4. return foodId
deactivate Entity
Controller --> UI : 5. Thông báo thêm thành công
deactivate Controller
UI --> Actor : 6. Cập nhật giao diện Tủ lạnh
deactivate UI
@enduml
