@startuml
title Analysis Class Diagram - UC023 RemoveFood

class "RemoveFoodUI" as UI <<boundary>> {
  + selectFoodToRemove() : void
  + displayResult() : void
}
class "FoodManagementController" as Controller <<control>> {
  + removeFood(foodId: String) : void
}
class "PantryDB" as Entity <<entity>> {
  + deleteFoodData(foodId: String) : Boolean
}

Controller -- UI
Controller -- Entity
@enduml
